services:
  airflow:
    build:
      context: ./backend/airflow
      dockerfile: Dockerfile
    container_name: airflow
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__BASE_URL: https://auditapro.com.br/airflow
      AIRFLOW__WEBSERVER__WEB_SERVER_NAME: auditapro.com.br
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__WEBSERVER__WEB_SERVER_PREFIX: /airflow      
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - audita-net

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - audita-net

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django
    env_file:
      - .env
    volumes:
      - ./backend/django:/opt/django
      - static_volume:/opt/django/staticfiles
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      - audita-net

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/browser:/usr/share/nginx/html
      - static_volume:/opt/django/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - audita-net

volumes:
  postgres-db-volume:
  static_volume:

networks:
  audita-net:
