name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build Angular
      run: |
        cd frontend
        npm install
        npm run build

    - name: Copiar arquivos para o servidor via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "."
        target: "/caminho/no/servidor"

    - name: Executar comandos remotos via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          cd /caminho/no/servidor
          docker-compose down
          docker-compose up --build -d
          docker exec nome_do_container_django python manage.py migrate
