# Generated by Django 5.1.7 on 2025-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=100)),
                ('orgao', models.CharField(max_length=255)),
                ('data_publicacao', models.DateField()),
                ('link_pdf', models.URLField(max_length=500)),
                ('edicao', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('id_materia', models.CharField(max_length=50, unique=True)),
                ('identifica', models.TextField()),
                ('texto_completo', models.TextField()),
                ('registro', models.CharField(blank=True, max_length=100, null=True)),
                ('auditado', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diario_oficial',
                'ordering': ['-data_publicacao'],
                'indexes': [models.Index(fields=['ano', 'mes', 'orgao'], name='diario_ofic_ano_b44939_idx'), models.Index(fields=['data_publicacao'], name='diario_ofic_data_pu_8adfe7_idx'), models.Index(fields=['auditado'], name='diario_ofic_auditad_14c94d_idx'), models.Index(fields=['id_materia'], name='diario_ofic_id_mate_8f50b7_idx')],
            },
        ),
    ]
